/* 
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * 
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TalonOne.Client.OpenAPIDateConverter;

namespace TalonOne.Model
{
    /// <summary>
    /// Holds a reference to the campaign, the coupon and the reason for which that coupon was rejected. Should only be present when there is a &#39;rejectCoupon&#39; effect.
    /// </summary>
    [DataContract]
    public partial class CouponRejectionReason :  IEquatable<CouponRejectionReason>, IValidatableObject
    {
        /// <summary>
        /// Defines Reason
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ReasonEnum
        {
            /// <summary>
            /// Enum CouponNotFound for value: CouponNotFound
            /// </summary>
            [EnumMember(Value = "CouponNotFound")]
            CouponNotFound = 1,

            /// <summary>
            /// Enum CouponPartOfNotRunningCampaign for value: CouponPartOfNotRunningCampaign
            /// </summary>
            [EnumMember(Value = "CouponPartOfNotRunningCampaign")]
            CouponPartOfNotRunningCampaign = 2,

            /// <summary>
            /// Enum CampaignLimitReached for value: CampaignLimitReached
            /// </summary>
            [EnumMember(Value = "CampaignLimitReached")]
            CampaignLimitReached = 3,

            /// <summary>
            /// Enum ProfileLimitReached for value: ProfileLimitReached
            /// </summary>
            [EnumMember(Value = "ProfileLimitReached")]
            ProfileLimitReached = 4,

            /// <summary>
            /// Enum CouponRecipientDoesNotMatch for value: CouponRecipientDoesNotMatch
            /// </summary>
            [EnumMember(Value = "CouponRecipientDoesNotMatch")]
            CouponRecipientDoesNotMatch = 5,

            /// <summary>
            /// Enum CouponExpired for value: CouponExpired
            /// </summary>
            [EnumMember(Value = "CouponExpired")]
            CouponExpired = 6,

            /// <summary>
            /// Enum CouponStartDateInFuture for value: CouponStartDateInFuture
            /// </summary>
            [EnumMember(Value = "CouponStartDateInFuture")]
            CouponStartDateInFuture = 7,

            /// <summary>
            /// Enum CouponRejectedByCondition for value: CouponRejectedByCondition
            /// </summary>
            [EnumMember(Value = "CouponRejectedByCondition")]
            CouponRejectedByCondition = 8,

            /// <summary>
            /// Enum EffectCouldNotBeApplied for value: EffectCouldNotBeApplied
            /// </summary>
            [EnumMember(Value = "EffectCouldNotBeApplied")]
            EffectCouldNotBeApplied = 9,

            /// <summary>
            /// Enum CouponPartOfNotTriggeredCampaign for value: CouponPartOfNotTriggeredCampaign
            /// </summary>
            [EnumMember(Value = "CouponPartOfNotTriggeredCampaign")]
            CouponPartOfNotTriggeredCampaign = 10,

            /// <summary>
            /// Enum CouponReservationRequired for value: CouponReservationRequired
            /// </summary>
            [EnumMember(Value = "CouponReservationRequired")]
            CouponReservationRequired = 11,

            /// <summary>
            /// Enum ProfileRequired for value: ProfileRequired
            /// </summary>
            [EnumMember(Value = "ProfileRequired")]
            ProfileRequired = 12

        }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [DataMember(Name="reason", EmitDefaultValue=false)]
        public ReasonEnum Reason { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CouponRejectionReason" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CouponRejectionReason() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CouponRejectionReason" /> class.
        /// </summary>
        /// <param name="campaignId">campaignId (required).</param>
        /// <param name="couponId">couponId (required).</param>
        /// <param name="reason">reason (required).</param>
        public CouponRejectionReason(int campaignId = default(int), int couponId = default(int), ReasonEnum reason = default(ReasonEnum))
        {
            this.CampaignId = campaignId;
            this.CouponId = couponId;
            this.Reason = reason;
        }
        
        /// <summary>
        /// Gets or Sets CampaignId
        /// </summary>
        [DataMember(Name="campaignId", EmitDefaultValue=false)]
        public int CampaignId { get; set; }

        /// <summary>
        /// Gets or Sets CouponId
        /// </summary>
        [DataMember(Name="couponId", EmitDefaultValue=false)]
        public int CouponId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CouponRejectionReason {\n");
            sb.Append("  CampaignId: ").Append(CampaignId).Append("\n");
            sb.Append("  CouponId: ").Append(CouponId).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CouponRejectionReason);
        }

        /// <summary>
        /// Returns true if CouponRejectionReason instances are equal
        /// </summary>
        /// <param name="input">Instance of CouponRejectionReason to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CouponRejectionReason input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CampaignId == input.CampaignId ||
                    this.CampaignId.Equals(input.CampaignId)
                ) && 
                (
                    this.CouponId == input.CouponId ||
                    this.CouponId.Equals(input.CouponId)
                ) && 
                (
                    this.Reason == input.Reason ||
                    this.Reason.Equals(input.Reason)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.CampaignId.GetHashCode();
                hashCode = hashCode * 59 + this.CouponId.GetHashCode();
                hashCode = hashCode * 59 + this.Reason.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
