/* 
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * 
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TalonOne.Client.OpenAPIDateConverter;

namespace TalonOne.Model
{
    /// <summary>
    /// CouponsNotificationPolicy
    /// </summary>
    [DataContract]
    public partial class CouponsNotificationPolicy :  IEquatable<CouponsNotificationPolicy>, IValidatableObject
    {
        /// <summary>
        /// Defines Scopes
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ScopesEnum
        {
            /// <summary>
            /// Enum All for value: all
            /// </summary>
            [EnumMember(Value = "all")]
            All = 1,

            /// <summary>
            /// Enum Campaignmanager for value: campaign_manager
            /// </summary>
            [EnumMember(Value = "campaign_manager")]
            Campaignmanager = 2,

            /// <summary>
            /// Enum Managementapi for value: management_api
            /// </summary>
            [EnumMember(Value = "management_api")]
            Managementapi = 3,

            /// <summary>
            /// Enum Ruleengine for value: rule_engine
            /// </summary>
            [EnumMember(Value = "rule_engine")]
            Ruleengine = 4

        }


        /// <summary>
        /// Gets or Sets Scopes
        /// </summary>
        [DataMember(Name="scopes", EmitDefaultValue=false)]
        public List<ScopesEnum> Scopes { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CouponsNotificationPolicy" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CouponsNotificationPolicy() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CouponsNotificationPolicy" /> class.
        /// </summary>
        /// <param name="name">Notification name. (required).</param>
        /// <param name="scopes">scopes (required).</param>
        /// <param name="batchingEnabled">Indicates whether batching is activated. (default to true).</param>
        /// <param name="includeData">Indicates whether to include all generated coupons. If &#x60;false&#x60;, only the &#x60;batchId&#x60; of the generated coupons is included..</param>
        /// <param name="batchSize">The required size of each batch of data. This value applies only when &#x60;batchingEnabled&#x60; is &#x60;true&#x60;..</param>
        public CouponsNotificationPolicy(string name = default(string), List<ScopesEnum> scopes = default(List<ScopesEnum>), bool batchingEnabled = true, bool includeData = default(bool), int batchSize = default(int))
        {
            // to ensure "name" is required (not null)
            this.Name = name ?? throw new ArgumentNullException("name is a required property for CouponsNotificationPolicy and cannot be null");
            // to ensure "scopes" is required (not null)
            this.Scopes = scopes ?? throw new ArgumentNullException("scopes is a required property for CouponsNotificationPolicy and cannot be null");
            this.BatchingEnabled = batchingEnabled;
            this.IncludeData = includeData;
            this.BatchSize = batchSize;
        }
        
        /// <summary>
        /// Notification name.
        /// </summary>
        /// <value>Notification name.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Indicates whether batching is activated.
        /// </summary>
        /// <value>Indicates whether batching is activated.</value>
        [DataMember(Name="batchingEnabled", EmitDefaultValue=false)]
        public bool BatchingEnabled { get; set; }

        /// <summary>
        /// Indicates whether to include all generated coupons. If &#x60;false&#x60;, only the &#x60;batchId&#x60; of the generated coupons is included.
        /// </summary>
        /// <value>Indicates whether to include all generated coupons. If &#x60;false&#x60;, only the &#x60;batchId&#x60; of the generated coupons is included.</value>
        [DataMember(Name="includeData", EmitDefaultValue=false)]
        public bool IncludeData { get; set; }

        /// <summary>
        /// The required size of each batch of data. This value applies only when &#x60;batchingEnabled&#x60; is &#x60;true&#x60;.
        /// </summary>
        /// <value>The required size of each batch of data. This value applies only when &#x60;batchingEnabled&#x60; is &#x60;true&#x60;.</value>
        [DataMember(Name="batchSize", EmitDefaultValue=false)]
        public int BatchSize { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CouponsNotificationPolicy {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Scopes: ").Append(Scopes).Append("\n");
            sb.Append("  BatchingEnabled: ").Append(BatchingEnabled).Append("\n");
            sb.Append("  IncludeData: ").Append(IncludeData).Append("\n");
            sb.Append("  BatchSize: ").Append(BatchSize).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CouponsNotificationPolicy);
        }

        /// <summary>
        /// Returns true if CouponsNotificationPolicy instances are equal
        /// </summary>
        /// <param name="input">Instance of CouponsNotificationPolicy to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CouponsNotificationPolicy input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Scopes == input.Scopes ||
                    this.Scopes.SequenceEqual(input.Scopes)
                ) && 
                (
                    this.BatchingEnabled == input.BatchingEnabled ||
                    this.BatchingEnabled.Equals(input.BatchingEnabled)
                ) && 
                (
                    this.IncludeData == input.IncludeData ||
                    this.IncludeData.Equals(input.IncludeData)
                ) && 
                (
                    this.BatchSize == input.BatchSize ||
                    this.BatchSize.Equals(input.BatchSize)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                hashCode = hashCode * 59 + this.Scopes.GetHashCode();
                hashCode = hashCode * 59 + this.BatchingEnabled.GetHashCode();
                hashCode = hashCode * 59 + this.IncludeData.GetHashCode();
                hashCode = hashCode * 59 + this.BatchSize.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) minLength
            if(this.Name != null && this.Name.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            yield break;
        }
    }

}
