/* 
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * 
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TalonOne.Client.OpenAPIDateConverter;

namespace TalonOne.Model
{
    /// <summary>
    /// A block that creates a coupon code.
    /// </summary>
    [DataContract]
    public partial class CreateCouponBlock :  IEquatable<CreateCouponBlock>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCouponBlock" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateCouponBlock() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCouponBlock" /> class.
        /// </summary>
        /// <param name="type">Identifies the block variant and determines which additional properties are present in it. (required).</param>
        /// <param name="campaignId">The ID of the campaign in which the coupon code is created. (required).</param>
        /// <param name="recipientId">The integration ID of the customer that is allowed to redeem this coupon. (required).</param>
        /// <param name="storeInSession">When &#x60;true&#x60;, the coupon is stored in the session. (required).</param>
        /// <param name="usageLimit">The number of times the coupon code can be redeemed. &#x60;0&#x60; means unlimited redemptions, but any campaign usage limits still apply. Either a numeric scalar or a &#x60;{{expression}}&#x60; string that resolves to a number at evaluation time. .</param>
        /// <param name="discountLimit">The total discount value that the code can give. Typically used to represent a gift card value. Either a numeric scalar or a &#x60;{{expression}}&#x60; string that resolves to a number at evaluation time. .</param>
        /// <param name="startDate">Timestamp at which point the coupon becomes valid..</param>
        /// <param name="expiryDate">Expiration date of the coupon. Coupon never expires if this is omitted..</param>
        /// <param name="attributes">Custom attributes associated with this coupon code..</param>
        /// <param name="validCharacters">Characters used to generate the random parts of a code..</param>
        /// <param name="pattern">The pattern used to generate codes, such as coupon codes, referral codes, and loyalty cards. The character &#x60;#&#x60; is a placeholder and is replaced by a random character from the &#x60;validCharacters&#x60; set. .</param>
        public CreateCouponBlock(string type = default(string), Object campaignId = default(Object), string recipientId = default(string), bool storeInSession = default(bool), Object usageLimit = default(Object), Object discountLimit = default(Object), Object startDate = default(Object), Object expiryDate = default(Object), Object attributes = default(Object), string validCharacters = default(string), string pattern = default(string))
        {
            // to ensure "type" is required (not null)
            this.Type = type ?? throw new ArgumentNullException("type is a required property for CreateCouponBlock and cannot be null");
            // to ensure "campaignId" is required (not null)
            this.CampaignId = campaignId ?? throw new ArgumentNullException("campaignId is a required property for CreateCouponBlock and cannot be null");
            // to ensure "recipientId" is required (not null)
            this.RecipientId = recipientId ?? throw new ArgumentNullException("recipientId is a required property for CreateCouponBlock and cannot be null");
            this.StoreInSession = storeInSession;
            this.UsageLimit = usageLimit;
            this.DiscountLimit = discountLimit;
            this.StartDate = startDate;
            this.ExpiryDate = expiryDate;
            this.Attributes = attributes;
            this.ValidCharacters = validCharacters;
            this.Pattern = pattern;
        }
        
        /// <summary>
        /// Unique identifier for this block.
        /// </summary>
        /// <value>Unique identifier for this block.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; private set; }

        /// <summary>
        /// Identifies the block variant and determines which additional properties are present in it.
        /// </summary>
        /// <value>Identifies the block variant and determines which additional properties are present in it.</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Semantic labels attached to this block.
        /// </summary>
        /// <value>Semantic labels attached to this block.</value>
        [DataMember(Name="tags", EmitDefaultValue=false)]
        public List<string> Tags { get; private set; }

        /// <summary>
        /// The ID of the campaign in which the coupon code is created.
        /// </summary>
        /// <value>The ID of the campaign in which the coupon code is created.</value>
        [DataMember(Name="campaignId", EmitDefaultValue=false)]
        public Object CampaignId { get; set; }

        /// <summary>
        /// The integration ID of the customer that is allowed to redeem this coupon.
        /// </summary>
        /// <value>The integration ID of the customer that is allowed to redeem this coupon.</value>
        [DataMember(Name="recipientId", EmitDefaultValue=false)]
        public string RecipientId { get; set; }

        /// <summary>
        /// When &#x60;true&#x60;, the coupon is stored in the session.
        /// </summary>
        /// <value>When &#x60;true&#x60;, the coupon is stored in the session.</value>
        [DataMember(Name="storeInSession", EmitDefaultValue=false)]
        public bool StoreInSession { get; set; }

        /// <summary>
        /// The number of times the coupon code can be redeemed. &#x60;0&#x60; means unlimited redemptions, but any campaign usage limits still apply. Either a numeric scalar or a &#x60;{{expression}}&#x60; string that resolves to a number at evaluation time. 
        /// </summary>
        /// <value>The number of times the coupon code can be redeemed. &#x60;0&#x60; means unlimited redemptions, but any campaign usage limits still apply. Either a numeric scalar or a &#x60;{{expression}}&#x60; string that resolves to a number at evaluation time. </value>
        [DataMember(Name="usageLimit", EmitDefaultValue=false)]
        public Object UsageLimit { get; set; }

        /// <summary>
        /// The total discount value that the code can give. Typically used to represent a gift card value. Either a numeric scalar or a &#x60;{{expression}}&#x60; string that resolves to a number at evaluation time. 
        /// </summary>
        /// <value>The total discount value that the code can give. Typically used to represent a gift card value. Either a numeric scalar or a &#x60;{{expression}}&#x60; string that resolves to a number at evaluation time. </value>
        [DataMember(Name="discountLimit", EmitDefaultValue=false)]
        public Object DiscountLimit { get; set; }

        /// <summary>
        /// Timestamp at which point the coupon becomes valid.
        /// </summary>
        /// <value>Timestamp at which point the coupon becomes valid.</value>
        [DataMember(Name="startDate", EmitDefaultValue=false)]
        public Object StartDate { get; set; }

        /// <summary>
        /// Expiration date of the coupon. Coupon never expires if this is omitted.
        /// </summary>
        /// <value>Expiration date of the coupon. Coupon never expires if this is omitted.</value>
        [DataMember(Name="expiryDate", EmitDefaultValue=false)]
        public Object ExpiryDate { get; set; }

        /// <summary>
        /// Custom attributes associated with this coupon code.
        /// </summary>
        /// <value>Custom attributes associated with this coupon code.</value>
        [DataMember(Name="attributes", EmitDefaultValue=false)]
        public Object Attributes { get; set; }

        /// <summary>
        /// Characters used to generate the random parts of a code.
        /// </summary>
        /// <value>Characters used to generate the random parts of a code.</value>
        [DataMember(Name="validCharacters", EmitDefaultValue=false)]
        public string ValidCharacters { get; set; }

        /// <summary>
        /// The pattern used to generate codes, such as coupon codes, referral codes, and loyalty cards. The character &#x60;#&#x60; is a placeholder and is replaced by a random character from the &#x60;validCharacters&#x60; set. 
        /// </summary>
        /// <value>The pattern used to generate codes, such as coupon codes, referral codes, and loyalty cards. The character &#x60;#&#x60; is a placeholder and is replaced by a random character from the &#x60;validCharacters&#x60; set. </value>
        [DataMember(Name="pattern", EmitDefaultValue=false)]
        public string Pattern { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateCouponBlock {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  CampaignId: ").Append(CampaignId).Append("\n");
            sb.Append("  RecipientId: ").Append(RecipientId).Append("\n");
            sb.Append("  StoreInSession: ").Append(StoreInSession).Append("\n");
            sb.Append("  UsageLimit: ").Append(UsageLimit).Append("\n");
            sb.Append("  DiscountLimit: ").Append(DiscountLimit).Append("\n");
            sb.Append("  StartDate: ").Append(StartDate).Append("\n");
            sb.Append("  ExpiryDate: ").Append(ExpiryDate).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("  ValidCharacters: ").Append(ValidCharacters).Append("\n");
            sb.Append("  Pattern: ").Append(Pattern).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateCouponBlock);
        }

        /// <summary>
        /// Returns true if CreateCouponBlock instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateCouponBlock to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateCouponBlock input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Tags == input.Tags ||
                    this.Tags != null &&
                    input.Tags != null &&
                    this.Tags.SequenceEqual(input.Tags)
                ) && 
                (
                    this.CampaignId == input.CampaignId ||
                    (this.CampaignId != null &&
                    this.CampaignId.Equals(input.CampaignId))
                ) && 
                (
                    this.RecipientId == input.RecipientId ||
                    (this.RecipientId != null &&
                    this.RecipientId.Equals(input.RecipientId))
                ) && 
                (
                    this.StoreInSession == input.StoreInSession ||
                    this.StoreInSession.Equals(input.StoreInSession)
                ) && 
                (
                    this.UsageLimit == input.UsageLimit ||
                    (this.UsageLimit != null &&
                    this.UsageLimit.Equals(input.UsageLimit))
                ) && 
                (
                    this.DiscountLimit == input.DiscountLimit ||
                    (this.DiscountLimit != null &&
                    this.DiscountLimit.Equals(input.DiscountLimit))
                ) && 
                (
                    this.StartDate == input.StartDate ||
                    (this.StartDate != null &&
                    this.StartDate.Equals(input.StartDate))
                ) && 
                (
                    this.ExpiryDate == input.ExpiryDate ||
                    (this.ExpiryDate != null &&
                    this.ExpiryDate.Equals(input.ExpiryDate))
                ) && 
                (
                    this.Attributes == input.Attributes ||
                    (this.Attributes != null &&
                    this.Attributes.Equals(input.Attributes))
                ) && 
                (
                    this.ValidCharacters == input.ValidCharacters ||
                    (this.ValidCharacters != null &&
                    this.ValidCharacters.Equals(input.ValidCharacters))
                ) && 
                (
                    this.Pattern == input.Pattern ||
                    (this.Pattern != null &&
                    this.Pattern.Equals(input.Pattern))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Tags != null)
                    hashCode = hashCode * 59 + this.Tags.GetHashCode();
                if (this.CampaignId != null)
                    hashCode = hashCode * 59 + this.CampaignId.GetHashCode();
                if (this.RecipientId != null)
                    hashCode = hashCode * 59 + this.RecipientId.GetHashCode();
                hashCode = hashCode * 59 + this.StoreInSession.GetHashCode();
                if (this.UsageLimit != null)
                    hashCode = hashCode * 59 + this.UsageLimit.GetHashCode();
                if (this.DiscountLimit != null)
                    hashCode = hashCode * 59 + this.DiscountLimit.GetHashCode();
                if (this.StartDate != null)
                    hashCode = hashCode * 59 + this.StartDate.GetHashCode();
                if (this.ExpiryDate != null)
                    hashCode = hashCode * 59 + this.ExpiryDate.GetHashCode();
                if (this.Attributes != null)
                    hashCode = hashCode * 59 + this.Attributes.GetHashCode();
                if (this.ValidCharacters != null)
                    hashCode = hashCode * 59 + this.ValidCharacters.GetHashCode();
                if (this.Pattern != null)
                    hashCode = hashCode * 59 + this.Pattern.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
