/* 
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * 
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TalonOne.Client.OpenAPIDateConverter;

namespace TalonOne.Model
{
    /// <summary>
    /// ExcludePriceObservationsRequest
    /// </summary>
    [DataContract]
    public partial class ExcludePriceObservationsRequest :  IEquatable<ExcludePriceObservationsRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExcludePriceObservationsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ExcludePriceObservationsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ExcludePriceObservationsRequest" /> class.
        /// </summary>
        /// <param name="ids">A list of historical price IDs to exclude from best prior price calculation. Must contain between 1 and 1000 IDs. All IDs must be valid &#x60;id&#x60; values obtained from the [Get summary of price history](https://docs.talon.one/management-api#tag/Catalogs/operation/priceHistory.responses.200.history) endpoint, must belong to the specified Application, and must not already be excluded from best prior price calculation.  (required).</param>
        /// <param name="reason">The reason for excluding these historical price IDs. Applies to all IDs in the batch.  (required).</param>
        public ExcludePriceObservationsRequest(List<long> ids = default(List<long>), string reason = default(string))
        {
            // to ensure "ids" is required (not null)
            this.Ids = ids ?? throw new ArgumentNullException("ids is a required property for ExcludePriceObservationsRequest and cannot be null");
            // to ensure "reason" is required (not null)
            this.Reason = reason ?? throw new ArgumentNullException("reason is a required property for ExcludePriceObservationsRequest and cannot be null");
        }
        
        /// <summary>
        /// A list of historical price IDs to exclude from best prior price calculation. Must contain between 1 and 1000 IDs. All IDs must be valid &#x60;id&#x60; values obtained from the [Get summary of price history](https://docs.talon.one/management-api#tag/Catalogs/operation/priceHistory.responses.200.history) endpoint, must belong to the specified Application, and must not already be excluded from best prior price calculation. 
        /// </summary>
        /// <value>A list of historical price IDs to exclude from best prior price calculation. Must contain between 1 and 1000 IDs. All IDs must be valid &#x60;id&#x60; values obtained from the [Get summary of price history](https://docs.talon.one/management-api#tag/Catalogs/operation/priceHistory.responses.200.history) endpoint, must belong to the specified Application, and must not already be excluded from best prior price calculation. </value>
        [DataMember(Name="ids", EmitDefaultValue=false)]
        public List<long> Ids { get; set; }

        /// <summary>
        /// The reason for excluding these historical price IDs. Applies to all IDs in the batch. 
        /// </summary>
        /// <value>The reason for excluding these historical price IDs. Applies to all IDs in the batch. </value>
        [DataMember(Name="reason", EmitDefaultValue=false)]
        public string Reason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ExcludePriceObservationsRequest {\n");
            sb.Append("  Ids: ").Append(Ids).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ExcludePriceObservationsRequest);
        }

        /// <summary>
        /// Returns true if ExcludePriceObservationsRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ExcludePriceObservationsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ExcludePriceObservationsRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Ids == input.Ids ||
                    this.Ids != null &&
                    input.Ids != null &&
                    this.Ids.SequenceEqual(input.Ids)
                ) && 
                (
                    this.Reason == input.Reason ||
                    (this.Reason != null &&
                    this.Reason.Equals(input.Reason))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Ids != null)
                    hashCode = hashCode * 59 + this.Ids.GetHashCode();
                if (this.Reason != null)
                    hashCode = hashCode * 59 + this.Reason.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Reason (string) minLength
            if(this.Reason != null && this.Reason.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Reason, length must be greater than 1.", new [] { "Reason" });
            }

            yield break;
        }
    }

}
