/* 
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * 
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TalonOne.Client.OpenAPIDateConverter;

namespace TalonOne.Model
{
    /// <summary>
    /// GenerateCouponFailureSummary
    /// </summary>
    [DataContract]
    public partial class GenerateCouponFailureSummary :  IEquatable<GenerateCouponFailureSummary>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GenerateCouponFailureSummary" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GenerateCouponFailureSummary() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GenerateCouponFailureSummary" /> class.
        /// </summary>
        /// <param name="eventID">The ID of the event. (required).</param>
        /// <param name="language">The language the summary will be generated in..</param>
        public GenerateCouponFailureSummary(long eventID = default(long), string language = default(string))
        {
            this.EventID = eventID;
            this.Language = language;
        }
        
        /// <summary>
        /// The ID of the event.
        /// </summary>
        /// <value>The ID of the event.</value>
        [DataMember(Name="eventID", EmitDefaultValue=false)]
        public long EventID { get; set; }

        /// <summary>
        /// The language the summary will be generated in.
        /// </summary>
        /// <value>The language the summary will be generated in.</value>
        [DataMember(Name="language", EmitDefaultValue=false)]
        public string Language { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GenerateCouponFailureSummary {\n");
            sb.Append("  EventID: ").Append(EventID).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GenerateCouponFailureSummary);
        }

        /// <summary>
        /// Returns true if GenerateCouponFailureSummary instances are equal
        /// </summary>
        /// <param name="input">Instance of GenerateCouponFailureSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GenerateCouponFailureSummary input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.EventID == input.EventID ||
                    this.EventID.Equals(input.EventID)
                ) && 
                (
                    this.Language == input.Language ||
                    (this.Language != null &&
                    this.Language.Equals(input.Language))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.EventID.GetHashCode();
                if (this.Language != null)
                    hashCode = hashCode * 59 + this.Language.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
