/* 
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * 
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TalonOne.Client.OpenAPIDateConverter;

namespace TalonOne.Model
{
    /// <summary>
    /// This effect indicates that a discount that should be applied on a specific additional cost. It is triggered whenever a rule containing a **Discount additional cost** effect is validated.  Enabling [partial rewards](https://docs.talon.one/docs/product/applications/manage-general-settings#partial-rewards) allows a rule that would fail because of insufficient budget to pass. The rule still fails when the budget reaches 0. Use the &#x60;desiredValue&#x60; property to identify the original amount of loyalty points.
    /// </summary>
    [DataContract]
    public partial class SetDiscountPerAdditionalCostEffectProps :  IEquatable<SetDiscountPerAdditionalCostEffectProps>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetDiscountPerAdditionalCostEffectProps" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SetDiscountPerAdditionalCostEffectProps() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SetDiscountPerAdditionalCostEffectProps" /> class.
        /// </summary>
        /// <param name="name">The name of the discount. (required).</param>
        /// <param name="additionalCostId">The identifier of the additional cost. (required).</param>
        /// <param name="additionalCost">The API name of the additional cost. (required).</param>
        /// <param name="value">The monetary value of the discount to apply. (required).</param>
        /// <param name="desiredValue">_(Partial discounts enabled only)_ The monetary value of the discount to be applied without considering budget limitations..</param>
        public SetDiscountPerAdditionalCostEffectProps(string name = default(string), long additionalCostId = default(long), string additionalCost = default(string), decimal value = default(decimal), decimal desiredValue = default(decimal))
        {
            // to ensure "name" is required (not null)
            this.Name = name ?? throw new ArgumentNullException("name is a required property for SetDiscountPerAdditionalCostEffectProps and cannot be null");
            this.AdditionalCostId = additionalCostId;
            // to ensure "additionalCost" is required (not null)
            this.AdditionalCost = additionalCost ?? throw new ArgumentNullException("additionalCost is a required property for SetDiscountPerAdditionalCostEffectProps and cannot be null");
            this.Value = value;
            this.DesiredValue = desiredValue;
        }
        
        /// <summary>
        /// The name of the discount.
        /// </summary>
        /// <value>The name of the discount.</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// The identifier of the additional cost.
        /// </summary>
        /// <value>The identifier of the additional cost.</value>
        [DataMember(Name="additionalCostId", EmitDefaultValue=false)]
        public long AdditionalCostId { get; set; }

        /// <summary>
        /// The API name of the additional cost.
        /// </summary>
        /// <value>The API name of the additional cost.</value>
        [DataMember(Name="additionalCost", EmitDefaultValue=false)]
        public string AdditionalCost { get; set; }

        /// <summary>
        /// The monetary value of the discount to apply.
        /// </summary>
        /// <value>The monetary value of the discount to apply.</value>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public decimal Value { get; set; }

        /// <summary>
        /// _(Partial discounts enabled only)_ The monetary value of the discount to be applied without considering budget limitations.
        /// </summary>
        /// <value>_(Partial discounts enabled only)_ The monetary value of the discount to be applied without considering budget limitations.</value>
        [DataMember(Name="desiredValue", EmitDefaultValue=false)]
        public decimal DesiredValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SetDiscountPerAdditionalCostEffectProps {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  AdditionalCostId: ").Append(AdditionalCostId).Append("\n");
            sb.Append("  AdditionalCost: ").Append(AdditionalCost).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  DesiredValue: ").Append(DesiredValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SetDiscountPerAdditionalCostEffectProps);
        }

        /// <summary>
        /// Returns true if SetDiscountPerAdditionalCostEffectProps instances are equal
        /// </summary>
        /// <param name="input">Instance of SetDiscountPerAdditionalCostEffectProps to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SetDiscountPerAdditionalCostEffectProps input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.AdditionalCostId == input.AdditionalCostId ||
                    this.AdditionalCostId.Equals(input.AdditionalCostId)
                ) && 
                (
                    this.AdditionalCost == input.AdditionalCost ||
                    (this.AdditionalCost != null &&
                    this.AdditionalCost.Equals(input.AdditionalCost))
                ) && 
                (
                    this.Value == input.Value ||
                    this.Value.Equals(input.Value)
                ) && 
                (
                    this.DesiredValue == input.DesiredValue ||
                    this.DesiredValue.Equals(input.DesiredValue)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                hashCode = hashCode * 59 + this.AdditionalCostId.GetHashCode();
                if (this.AdditionalCost != null)
                    hashCode = hashCode * 59 + this.AdditionalCost.GetHashCode();
                hashCode = hashCode * 59 + this.Value.GetHashCode();
                hashCode = hashCode * 59 + this.DesiredValue.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
