/* 
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * 
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TalonOne.Client.OpenAPIDateConverter;

namespace TalonOne.Model
{
    /// <summary>
    /// TransferLoyaltyCard
    /// </summary>
    [DataContract]
    public partial class TransferLoyaltyCard :  IEquatable<TransferLoyaltyCard>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransferLoyaltyCard" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransferLoyaltyCard() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransferLoyaltyCard" /> class.
        /// </summary>
        /// <param name="newCardIdentifier">The alphanumeric identifier of the loyalty card.  (required).</param>
        /// <param name="blockReason">Reason for transferring and blocking the loyalty card. .</param>
        public TransferLoyaltyCard(string newCardIdentifier = default(string), string blockReason = default(string))
        {
            // to ensure "newCardIdentifier" is required (not null)
            this.NewCardIdentifier = newCardIdentifier ?? throw new ArgumentNullException("newCardIdentifier is a required property for TransferLoyaltyCard and cannot be null");
            this.BlockReason = blockReason;
        }
        
        /// <summary>
        /// The alphanumeric identifier of the loyalty card. 
        /// </summary>
        /// <value>The alphanumeric identifier of the loyalty card. </value>
        [DataMember(Name="newCardIdentifier", EmitDefaultValue=false)]
        public string NewCardIdentifier { get; set; }

        /// <summary>
        /// Reason for transferring and blocking the loyalty card. 
        /// </summary>
        /// <value>Reason for transferring and blocking the loyalty card. </value>
        [DataMember(Name="blockReason", EmitDefaultValue=false)]
        public string BlockReason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransferLoyaltyCard {\n");
            sb.Append("  NewCardIdentifier: ").Append(NewCardIdentifier).Append("\n");
            sb.Append("  BlockReason: ").Append(BlockReason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransferLoyaltyCard);
        }

        /// <summary>
        /// Returns true if TransferLoyaltyCard instances are equal
        /// </summary>
        /// <param name="input">Instance of TransferLoyaltyCard to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransferLoyaltyCard input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.NewCardIdentifier == input.NewCardIdentifier ||
                    (this.NewCardIdentifier != null &&
                    this.NewCardIdentifier.Equals(input.NewCardIdentifier))
                ) && 
                (
                    this.BlockReason == input.BlockReason ||
                    (this.BlockReason != null &&
                    this.BlockReason.Equals(input.BlockReason))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NewCardIdentifier != null)
                    hashCode = hashCode * 59 + this.NewCardIdentifier.GetHashCode();
                if (this.BlockReason != null)
                    hashCode = hashCode * 59 + this.BlockReason.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // NewCardIdentifier (string) maxLength
            if(this.NewCardIdentifier != null && this.NewCardIdentifier.Length > 108)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for NewCardIdentifier, length must be less than 108.", new [] { "NewCardIdentifier" });
            }

            // NewCardIdentifier (string) pattern
            Regex regexNewCardIdentifier = new Regex(@"^[A-Za-z0-9_-]*$", RegexOptions.CultureInvariant);
            if (false == regexNewCardIdentifier.Match(this.NewCardIdentifier).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for NewCardIdentifier, must match a pattern of " + regexNewCardIdentifier, new [] { "NewCardIdentifier" });
            }

            yield break;
        }
    }

}
