/* 
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * 
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TalonOne.Client.OpenAPIDateConverter;

namespace TalonOne.Model
{
    /// <summary>
    /// UpdateExperimentVariantArray
    /// </summary>
    [DataContract]
    public partial class UpdateExperimentVariantArray :  IEquatable<UpdateExperimentVariantArray>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateExperimentVariantArray" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateExperimentVariantArray() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateExperimentVariantArray" /> class.
        /// </summary>
        /// <param name="variants">Array of experiment variants to update (required).</param>
        public UpdateExperimentVariantArray(List<UpdateExperimentVariant> variants = default(List<UpdateExperimentVariant>))
        {
            // to ensure "variants" is required (not null)
            this.Variants = variants ?? throw new ArgumentNullException("variants is a required property for UpdateExperimentVariantArray and cannot be null");
        }
        
        /// <summary>
        /// Array of experiment variants to update
        /// </summary>
        /// <value>Array of experiment variants to update</value>
        [DataMember(Name="variants", EmitDefaultValue=false)]
        public List<UpdateExperimentVariant> Variants { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdateExperimentVariantArray {\n");
            sb.Append("  Variants: ").Append(Variants).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateExperimentVariantArray);
        }

        /// <summary>
        /// Returns true if UpdateExperimentVariantArray instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateExperimentVariantArray to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateExperimentVariantArray input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Variants == input.Variants ||
                    this.Variants != null &&
                    input.Variants != null &&
                    this.Variants.SequenceEqual(input.Variants)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Variants != null)
                    hashCode = hashCode * 59 + this.Variants.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
