/* 
 * Talon.One API
 *
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation- -v1-customer_profiles- -integrationId- -put 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TalonOne.Api;
using TalonOne.Model;
using TalonOne.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TalonOne.Test
{
    /// <summary>
    ///  Class for testing Account
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Account
        //private Account instance;

        public AccountTests()
        {
            // TODO uncomment below to create an instance of Account
            //instance = new Account();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Account
        /// </summary>
        [Fact]
        public void AccountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Account
            //Assert.IsInstanceOfType<Account> (instance, "variable 'instance' is a Account");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Fact]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'DomainName'
        /// </summary>
        [Fact]
        public void DomainNameTest()
        {
            // TODO unit test for the property 'DomainName'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'BillingEmail'
        /// </summary>
        [Fact]
        public void BillingEmailTest()
        {
            // TODO unit test for the property 'BillingEmail'
        }
        /// <summary>
        /// Test the property 'PlanName'
        /// </summary>
        [Fact]
        public void PlanNameTest()
        {
            // TODO unit test for the property 'PlanName'
        }
        /// <summary>
        /// Test the property 'PlanExpires'
        /// </summary>
        [Fact]
        public void PlanExpiresTest()
        {
            // TODO unit test for the property 'PlanExpires'
        }
        /// <summary>
        /// Test the property 'ApplicationLimit'
        /// </summary>
        [Fact]
        public void ApplicationLimitTest()
        {
            // TODO unit test for the property 'ApplicationLimit'
        }
        /// <summary>
        /// Test the property 'UserLimit'
        /// </summary>
        [Fact]
        public void UserLimitTest()
        {
            // TODO unit test for the property 'UserLimit'
        }
        /// <summary>
        /// Test the property 'CampaignLimit'
        /// </summary>
        [Fact]
        public void CampaignLimitTest()
        {
            // TODO unit test for the property 'CampaignLimit'
        }
        /// <summary>
        /// Test the property 'ApiLimit'
        /// </summary>
        [Fact]
        public void ApiLimitTest()
        {
            // TODO unit test for the property 'ApiLimit'
        }
        /// <summary>
        /// Test the property 'ApplicationCount'
        /// </summary>
        [Fact]
        public void ApplicationCountTest()
        {
            // TODO unit test for the property 'ApplicationCount'
        }
        /// <summary>
        /// Test the property 'UserCount'
        /// </summary>
        [Fact]
        public void UserCountTest()
        {
            // TODO unit test for the property 'UserCount'
        }
        /// <summary>
        /// Test the property 'CampaignsActiveCount'
        /// </summary>
        [Fact]
        public void CampaignsActiveCountTest()
        {
            // TODO unit test for the property 'CampaignsActiveCount'
        }
        /// <summary>
        /// Test the property 'CampaignsInactiveCount'
        /// </summary>
        [Fact]
        public void CampaignsInactiveCountTest()
        {
            // TODO unit test for the property 'CampaignsInactiveCount'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }

    }

}
