/* 
 * Talon.One API
 *
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation- -v1-customer_profiles- -integrationId- -put 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TalonOne.Api;
using TalonOne.Model;
using TalonOne.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TalonOne.Test
{
    /// <summary>
    ///  Class for testing Environment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnvironmentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Environment
        //private Environment instance;

        public EnvironmentTests()
        {
            // TODO uncomment below to create an instance of Environment
            //instance = new Environment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Environment
        /// </summary>
        [Fact]
        public void EnvironmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Environment
            //Assert.IsInstanceOfType<Environment> (instance, "variable 'instance' is a Environment");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Fact]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }
        /// <summary>
        /// Test the property 'Slots'
        /// </summary>
        [Fact]
        public void SlotsTest()
        {
            // TODO unit test for the property 'Slots'
        }
        /// <summary>
        /// Test the property 'Functions'
        /// </summary>
        [Fact]
        public void FunctionsTest()
        {
            // TODO unit test for the property 'Functions'
        }
        /// <summary>
        /// Test the property 'Templates'
        /// </summary>
        [Fact]
        public void TemplatesTest()
        {
            // TODO unit test for the property 'Templates'
        }
        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Fact]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }
        /// <summary>
        /// Test the property 'GiveawaysPools'
        /// </summary>
        [Fact]
        public void GiveawaysPoolsTest()
        {
            // TODO unit test for the property 'GiveawaysPools'
        }
        /// <summary>
        /// Test the property 'LoyaltyPrograms'
        /// </summary>
        [Fact]
        public void LoyaltyProgramsTest()
        {
            // TODO unit test for the property 'LoyaltyPrograms'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'AdditionalCosts'
        /// </summary>
        [Fact]
        public void AdditionalCostsTest()
        {
            // TODO unit test for the property 'AdditionalCosts'
        }
        /// <summary>
        /// Test the property 'Audiences'
        /// </summary>
        [Fact]
        public void AudiencesTest()
        {
            // TODO unit test for the property 'Audiences'
        }

    }

}
