/* 
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 
 *
 * 
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TalonOne.Api;
using TalonOne.Model;
using TalonOne.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TalonOne.Test
{
    /// <summary>
    ///  Class for testing GiveawayPoolNotificationData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GiveawayPoolNotificationDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GiveawayPoolNotificationData
        //private GiveawayPoolNotificationData instance;

        public GiveawayPoolNotificationDataTests()
        {
            // TODO uncomment below to create an instance of GiveawayPoolNotificationData
            //instance = new GiveawayPoolNotificationData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GiveawayPoolNotificationData
        /// </summary>
        [Fact]
        public void GiveawayPoolNotificationDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GiveawayPoolNotificationData
            //Assert.IsInstanceOfType<GiveawayPoolNotificationData> (instance, "variable 'instance' is a GiveawayPoolNotificationData");
        }


        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Fact]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }
        /// <summary>
        /// Test the property 'PoolId'
        /// </summary>
        [Fact]
        public void PoolIdTest()
        {
            // TODO unit test for the property 'PoolId'
        }
        /// <summary>
        /// Test the property 'PoolName'
        /// </summary>
        [Fact]
        public void PoolNameTest()
        {
            // TODO unit test for the property 'PoolName'
        }
        /// <summary>
        /// Test the property 'PoolDescription'
        /// </summary>
        [Fact]
        public void PoolDescriptionTest()
        {
            // TODO unit test for the property 'PoolDescription'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Fact]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }
        /// <summary>
        /// Test the property 'TotalCodes'
        /// </summary>
        [Fact]
        public void TotalCodesTest()
        {
            // TODO unit test for the property 'TotalCodes'
        }
        /// <summary>
        /// Test the property 'UsedCodes'
        /// </summary>
        [Fact]
        public void UsedCodesTest()
        {
            // TODO unit test for the property 'UsedCodes'
        }
        /// <summary>
        /// Test the property 'RemainingCodes'
        /// </summary>
        [Fact]
        public void RemainingCodesTest()
        {
            // TODO unit test for the property 'RemainingCodes'
        }
        /// <summary>
        /// Test the property 'ThresholdPercent'
        /// </summary>
        [Fact]
        public void ThresholdPercentTest()
        {
            // TODO unit test for the property 'ThresholdPercent'
        }

    }

}
