/* 
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * 
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TalonOne.Api;
using TalonOne.Model;
using TalonOne.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TalonOne.Test
{
    /// <summary>
    ///  Class for testing Meta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MetaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Meta
        //private Meta instance;

        public MetaTests()
        {
            // TODO uncomment below to create an instance of Meta
            //instance = new Meta();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Meta
        /// </summary>
        [Fact]
        public void MetaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Meta
            //Assert.IsInstanceOfType<Meta> (instance, "variable 'instance' is a Meta");
        }


        /// <summary>
        /// Test the property 'Campaigns'
        /// </summary>
        [Fact]
        public void CampaignsTest()
        {
            // TODO unit test for the property 'Campaigns'
        }
        /// <summary>
        /// Test the property 'Coupons'
        /// </summary>
        [Fact]
        public void CouponsTest()
        {
            // TODO unit test for the property 'Coupons'
        }
        /// <summary>
        /// Test the property 'CouponRejectionReason'
        /// </summary>
        [Fact]
        public void CouponRejectionReasonTest()
        {
            // TODO unit test for the property 'CouponRejectionReason'
        }
        /// <summary>
        /// Test the property 'ReferralRejectionReason'
        /// </summary>
        [Fact]
        public void ReferralRejectionReasonTest()
        {
            // TODO unit test for the property 'ReferralRejectionReason'
        }
        /// <summary>
        /// Test the property 'Warnings'
        /// </summary>
        [Fact]
        public void WarningsTest()
        {
            // TODO unit test for the property 'Warnings'
        }

    }

}
