/* 
 * Talon.One API
 *
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation- -v1-customer_profiles- -integrationId- -put 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TalonOne.Api;
using TalonOne.Model;
using TalonOne.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TalonOne.Test
{
    /// <summary>
    ///  Class for testing NewCampaignTemplate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewCampaignTemplateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewCampaignTemplate
        //private NewCampaignTemplate instance;

        public NewCampaignTemplateTests()
        {
            // TODO uncomment below to create an instance of NewCampaignTemplate
            //instance = new NewCampaignTemplate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewCampaignTemplate
        /// </summary>
        [Fact]
        public void NewCampaignTemplateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewCampaignTemplate
            //Assert.IsInstanceOfType<NewCampaignTemplate> (instance, "variable 'instance' is a NewCampaignTemplate");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Instructions'
        /// </summary>
        [Fact]
        public void InstructionsTest()
        {
            // TODO unit test for the property 'Instructions'
        }
        /// <summary>
        /// Test the property 'CampaignAttributes'
        /// </summary>
        [Fact]
        public void CampaignAttributesTest()
        {
            // TODO unit test for the property 'CampaignAttributes'
        }
        /// <summary>
        /// Test the property 'CouponAttributes'
        /// </summary>
        [Fact]
        public void CouponAttributesTest()
        {
            // TODO unit test for the property 'CouponAttributes'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'ActiveRulesetId'
        /// </summary>
        [Fact]
        public void ActiveRulesetIdTest()
        {
            // TODO unit test for the property 'ActiveRulesetId'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Fact]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }
        /// <summary>
        /// Test the property 'CouponSettings'
        /// </summary>
        [Fact]
        public void CouponSettingsTest()
        {
            // TODO unit test for the property 'CouponSettings'
        }
        /// <summary>
        /// Test the property 'ReferralSettings'
        /// </summary>
        [Fact]
        public void ReferralSettingsTest()
        {
            // TODO unit test for the property 'ReferralSettings'
        }
        /// <summary>
        /// Test the property 'Limits'
        /// </summary>
        [Fact]
        public void LimitsTest()
        {
            // TODO unit test for the property 'Limits'
        }
        /// <summary>
        /// Test the property 'TemplateParams'
        /// </summary>
        [Fact]
        public void TemplateParamsTest()
        {
            // TODO unit test for the property 'TemplateParams'
        }

    }

}
