/* 
 * Talon.One API
 *
 * The Talon.One API is used to manage applications and campaigns, as well as to integrate with your application. The operations in the _Integration API_ section are used to integrate with our platform, while the other operations are used to manage applications and campaigns.  ### Where is the API?  The API is available at the same hostname as these docs. For example, if you are reading this page at `https://mycompany.talon.one/docs/api/`, the URL for the [updateCustomerProfile][] operation is `https://mycompany.talon.one/v1/customer_profiles/id`  [updateCustomerProfile]: #operation- -v1-customer_profiles- -integrationId- -put 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TalonOne.Api;
using TalonOne.Model;
using TalonOne.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TalonOne.Test
{
    /// <summary>
    ///  Class for testing NewLoyaltyProgram
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewLoyaltyProgramTests
    {
        // TODO uncomment below to declare an instance variable for NewLoyaltyProgram
        //private NewLoyaltyProgram instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NewLoyaltyProgram
            //instance = new NewLoyaltyProgram();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewLoyaltyProgram
        /// </summary>
        [Test]
        public void NewLoyaltyProgramInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" NewLoyaltyProgram
            //Assert.IsInstanceOf(typeof(NewLoyaltyProgram), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'SubscribedApplications'
        /// </summary>
        [Test]
        public void SubscribedApplicationsTest()
        {
            // TODO unit test for the property 'SubscribedApplications'
        }
        /// <summary>
        /// Test the property 'DefaultValidity'
        /// </summary>
        [Test]
        public void DefaultValidityTest()
        {
            // TODO unit test for the property 'DefaultValidity'
        }
        /// <summary>
        /// Test the property 'DefaultPending'
        /// </summary>
        [Test]
        public void DefaultPendingTest()
        {
            // TODO unit test for the property 'DefaultPending'
        }
        /// <summary>
        /// Test the property 'AllowSubledger'
        /// </summary>
        [Test]
        public void AllowSubledgerTest()
        {
            // TODO unit test for the property 'AllowSubledger'
        }

    }

}
