/* 
 * Talon.One API
 *
 * Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 
 *
 * 
 * Contact: devs@talon.one
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TalonOne.Api;
using TalonOne.Model;
using TalonOne.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TalonOne.Test
{
    /// <summary>
    ///  Class for testing WebhookWithOutgoingIntegrationDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookWithOutgoingIntegrationDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookWithOutgoingIntegrationDetails
        //private WebhookWithOutgoingIntegrationDetails instance;

        public WebhookWithOutgoingIntegrationDetailsTests()
        {
            // TODO uncomment below to create an instance of WebhookWithOutgoingIntegrationDetails
            //instance = new WebhookWithOutgoingIntegrationDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookWithOutgoingIntegrationDetails
        /// </summary>
        [Fact]
        public void WebhookWithOutgoingIntegrationDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebhookWithOutgoingIntegrationDetails
            //Assert.IsInstanceOfType<WebhookWithOutgoingIntegrationDetails> (instance, "variable 'instance' is a WebhookWithOutgoingIntegrationDetails");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Fact]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }
        /// <summary>
        /// Test the property 'ApplicationIds'
        /// </summary>
        [Fact]
        public void ApplicationIdsTest()
        {
            // TODO unit test for the property 'ApplicationIds'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Verb'
        /// </summary>
        [Fact]
        public void VerbTest()
        {
            // TODO unit test for the property 'Verb'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Headers'
        /// </summary>
        [Fact]
        public void HeadersTest()
        {
            // TODO unit test for the property 'Headers'
        }
        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }
        /// <summary>
        /// Test the property 'Params'
        /// </summary>
        [Fact]
        public void ParamsTest()
        {
            // TODO unit test for the property 'Params'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'OutgoingIntegrationTemplateId'
        /// </summary>
        [Fact]
        public void OutgoingIntegrationTemplateIdTest()
        {
            // TODO unit test for the property 'OutgoingIntegrationTemplateId'
        }
        /// <summary>
        /// Test the property 'OutgoingIntegrationTypeId'
        /// </summary>
        [Fact]
        public void OutgoingIntegrationTypeIdTest()
        {
            // TODO unit test for the property 'OutgoingIntegrationTypeId'
        }
        /// <summary>
        /// Test the property 'OutgoingIntegrationTypeName'
        /// </summary>
        [Fact]
        public void OutgoingIntegrationTypeNameTest()
        {
            // TODO unit test for the property 'OutgoingIntegrationTypeName'
        }

    }

}
